# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E6phkyD02K_8rZsMbDq7EES8VKtrti6v

# Basic Python

## 1. Split this string
"""

s = "Hi there Sam!"

s.split()

"""## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742

print('The diameter of{ } is')

"""## 3. In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

"""# Numpy"""

import numpy as np

"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

a = np.zeros(10)

a

"""## 5. Create an array of all the even integers from 20 to 35"""

b = np.ones(10)*5
b

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

c = np.arange(0,9).reshape(3,3)
c

"""## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate((a,b),axis=0)

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd

d = {"fruits":["mango","orange","apple"],"color":["yellow","orange","red"]}
df = pd.DataFrame(d)
df

"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

P = pd.date_range(start='1-1-2023',end='10-2-2023')
for val in P:
  print(val);

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

df = pd.DataFrame(lists)
df